name: Pull Request Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.2
      - name: JDK 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: 'gradle'

      - name: Gradle Build
        runs: |
          ./gradlew build --parallel
      - name: Coverage Report
        uses: madrapps/jacoco-report@v1.6.1
        with:
          token: ${{ secrets.GITHUB }}
          title: Code Converage Report
          update-comment: true
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          paths: |
            ${{ github.workspace }}/**/build/jacoco/jacoco.xml


